Feature/tweet
shinonome-inc/backend-final-assignment-motoaki pull request #4
Opened 2023-12-03 11:39 UTC by nakajimamoto340

## 受講生の確認事項

- [x] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [x] Django Adminに，今まで作成したモデルを全て登録した
- [x] テスト要件のテストを全て実装した
- [x] CI が全て通った

## １次レビュアーの確認事項

- [x] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-12-06 02:28 UTC, shang-sin requested changes
数点コメントしました！
よく分からない部分や間違っている箇所があれば遠慮なく教えていただけるとありがたいです．

2023-12-06 02:28 UTC, morita-y9 commented on tweets/models.py
> +        return f"{self.user.username} - {self.content}"
要件には無いので修正はお任せしますが，新しいツイートが上に来るようにするとさらにユーザーが使いやすくなると思います！(modelとViewどちらでも付け加えることができます．)

2023-12-06 02:28 UTC, shang-sin commented on tweets/models.py
> +        return f"{self.user.username} - {self.content}"
管理者サイトを使っていないならいらないかなと思いました．(他の用途で使っているなら教えて欲しいです．)　でも管理者サイトを使ってみるのもいいと思います！

2023-12-06 02:28 UTC, shang-sin commented on accounts/views.py
> +        )
ここでツイート一覧は取得できているんですけど，Htmlを記述していなくて表示されてないのでUserProfileのHtmlファイルに書き足してほしいです！

2023-12-06 02:28 UTC, shang-sin commented on tweets/views.py
> +    context_object_name = "tweets"
tweet_delete.htmlで使ってないのでcontext_object_nameはいらないと思います！

2023-12-06 03:18 UTC, shang-sin requested changes

2023-12-06 03:18 UTC, shang-sin commented on tweets/tests.py
テストなんですけど，テスト項目を満たしていない部分が多いのでもう一度確認してみてください．
https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=119218931

2023-12-09 02:05 UTC, morita-y9 approved these changes

2023-12-09 02:06 UTC, morita-y9 commented
いいと思います！お疲れ様です．

2023-12-12 06:41 UTC, kenketsu reviewed
tweets/admin.py にtweetのモデルを登録してください

2023-12-12 06:41 UTC, kenketsu commented on tweets/forms.py
使っていないファイルなので消しましょう

2023-12-16 11:11 UTC, merged