feature/follow
shinonome-inc/backend-final-assignment-motoaki pull request #5
Opened 2023-12-08 14:13 UTC by nakajimamoto340

## 受講生の確認事項

- [x] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [x] Django Adminに，今まで作成したモデルを全て登録した
- [x] テスト要件のテストを全て実装した
- [x] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-01-01 15:06 UTC, JunyaMakita reviewed
フォロー機能とは別に気になった点も記述しておきます！
①自分の環境で動かしたところ、ログアウトが上手くいかないのですが、ちょっとそちらでうまく機能しているか（ログアウトを実行した際にログイン画面に遷移している）の確認をお願いします。
②Twitter Cloneを押した際に今はwelcomeに遷移するようになっていると思うのですが、homeに遷移するほうがいいと思うので、特にこだわりがない場合はhomeに遷移するように変更したほうがいいかと思われます。その際に現在のHomeViewのままだと、ログインしていないにも関わらずhomeに遷移してしまいますが、括弧内の順序を逆（ListView, LoginRequiredMixin⇒LoginRequiredMixin, ListView）にすることでログインしていない場合にhomeにリダイレクトされなくなります。順序があることに気を付けてください。

2024-01-01 15:06 UTC, JunyaMakita commented on templates/accounts/followerlist.html
> +<a href="{% url 'accounts:user_profile' username=user.username%}" class="btn">戻る</a>
フォロー・フォロワーリストの画面から戻るを押すとログインしているユーザーのプロフィールに遷移してしまうようになっているので、一つ前のURLに遷移するように変更してください。followinglist.htmlも同様です。

2024-01-01 15:06 UTC, JunyaMakita commented on accounts/tests.py
> +        )
test_success_postにてDBが削除されていることを確認するコードを追加してください。

2024-01-01 15:06 UTC, JunyaMakita commented on accounts/models.py
> +        ordering = ["-created_at"]
UniqueConstraintでユニーク制約を付与してください

2024-01-03 10:34 UTC, moto340 commented on templates/accounts/followerlist.html
> +<a href="{% url 'accounts:user_profile' username=user.username%}" class="btn">戻る</a>
フォロー、アンフォローリストのページの前のページのurlがaccounts:user_profileなのですがどのように変更すれば良いでしょうか。

2024-01-03 23:46 UTC, JunyaMakita commented on templates/accounts/followerlist.html
> +<a href="{% url 'accounts:user_profile' username=user.username%}" class="btn">戻る</a>
以下のサイトを参考にしてみてください。（今回は書き写すだけでできます！）
https://kuma-server.com/django-modoru/
https://codor.co.jp/django/how-to-make-back-button

2024-01-04 09:58 UTC, JunyaMakita commented
testとunique制約についてはOKです。
①フォローリストからの遷移に関しては上のサイトを参考にしてください。
②ログアウトは機能してますでしょうか。ログアウト機能はセキュリティの観点からPOSTメソッドを使用したほうが良いとされています。可能であれば「

2024-01-04 10:08 UTC, JunyaMakita commented
testとunique制約についてはOKです。
①フォローリストからの遷移に関しては上のサイトを参考にしてください。
②ログアウトは機能してますでしょうか。（ログアウト機能はセキュリティの観点からPOSTメソッドを使用したほうが良いとされています。）現在はGETメソッドですが動いていれば問題ないので、動いているかどうか教えてください。
③HomeViewの括弧内の順序は直されていますが、base.htmlのTwitter Cloneのボタンを押した際に遷移する場所がwelcomeのままになっています。<a>タグ内のURLを変更するだけで変更できるので、homeに遷移するようにしてみてください。

2024-01-05 08:03 UTC, JunyaMakita commented
今回の機能については動いているので良いと思います。
一次レビューLGTMです！

以下は今回の機能以外で気になった点です。
①TwitterCloneを押下した際にWelcome に遷移しているのですが、homeに遷移したほうが使い勝手がいいと思うので、特にこだわりがない場合は変更することをお勧めします。
②ログインしている際にSignupできるようになってしまっており、ログイン中に新規登録する必要はないはずなので、ログイン中にはsignupボタンが出ないようにしたほうがいいと思います。

2024-01-07 05:43 UTC, sui-false requested changes

2024-01-07 05:43 UTC, sui-false commented on templates/accounts/followinglist.html
> +    <li>{{ profile.followee.username }}</li>
各ユーザーのプロフィールへ飛べるようにしましょう

2024-01-07 05:43 UTC, sui-false commented on templates/accounts/followerlist.html
> +    <li>{{ profile.follower.username }}</li>
各ユーザーのプロフィールへ飛べるようにしましょう

2024-01-07 05:43 UTC, sui-false commented on accounts/tests.py
> +        user_follower_in_database = FriendShip.objects.filter(followee=self.user).count()
僕が間違ってたら申し訳ないですが、多分間違えてる気がするので読み直してみてください

2024-01-07 06:48 UTC, nakajimamoto340 commented on accounts/tests.py
> +        user_follower_in_database = FriendShip.objects.filter(followee=self.user).count()
間違えていると思われる箇所がわかりませんでした。もし不備がありましたら指摘していただけると幸いです。

2024-01-08 10:40 UTC, sui-false requested changes

2024-01-08 10:40 UTC, sui-false commented on templates/accounts/followerlist.html
> +    <li>{{ profile.follower.username }}</li>
説明が雑でした。
`<li>{{ profile.follower.username }}</li>`で各フォロワーのユーザーネームが表示されていますが、それをそのユーザーネームをクリックした際にそのフォロワーのプロフィールへ遷移できるようにしましょうという意図です。

2024-01-08 10:40 UTC, sui-false commented on templates/accounts/followinglist.html
> +    <li>{{ profile.followee.username }}</li>
上と同様です。

2024-01-08 10:40 UTC, sui-false commented on accounts/tests.py
> +        user_follower_in_database = FriendShip.objects.filter(followee=self.user).count()
僕もこの手のものはどっちがどっちか分からなくなってしまうので、自信ないですが、`user_followee_in_database`と`user_follower_in_database`が同じフィルターとなっていますが、これはあってますか？
文脈的にいずれかが`FriendShip.objects.filter(followee=self.user)`でもう片方が`FriendShip.objects.filter(follower=self.user)`となる気がしたのですが、、、

2024-01-11 14:25 UTC, nakajimamoto340 commented on templates/accounts/followerlist.html
> +    <li>{{ profile.follower.username }}</li>
コードが長いせいか保存すると勝手に改行されてしまい、表示される文字がフォロワーなどのユーザー名にならずにコードの文字列になってしまいます。勝手に改行されないようにする解決策はありますでしょうか。

2024-01-15 03:13 UTC, sui-false commented on templates/accounts/followerlist.html
> +    <li>{{ profile.follower.username }}</li>
フォーマッターが効きすぎているということでしょうか。通常、変数名であれば、途中で改行など起きない気もしますが、次のようにコメントすると無視できるようです。もし、むりそうならとりあえずプッシュしてくれれば、こちらでも見てみます。

https://dev.classmethod.jp/articles/black_block_string_auto_format/

2024-01-27 13:42 UTC, sui-false approved these changes

2024-01-27 13:42 UTC, merged